import { Inter } from "next/font/google";
import { dir } from 'i18next'
import { languages } from '../i18n/settings'
import "./globals.css";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Faction Quiz",
  description: "Generated by Elvira Vargas",
};

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
